name: flutter_lettutor
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  video_player: ^2.2.19
  chewie: ^1.3.0
  date_time_picker: ^2.1.0
  filter_list: ^1.0.1
  material_floating_search_bar: ^0.3.6
  flutter_neumorphic: ^3.2.0
  path_provider: ^2.0.9
  multi_select_flutter: ^4.1.2
  file_picker: ^4.5.1
  flutter_rating_bar: ^4.0.0
  intl: ^0.17.0
  uuid: ^3.0.6
  http: ^0.13.4
  shared_preferences: ^2.0.13
  country_picker: ^2.0.14
  modal_progress_hud: ^0.1.3
  recase: ^4.0.0
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  provider: ^6.0.2
  flutter_facebook_auth: ^4.3.0
  google_sign_in: ^5.3.0
  dio: ^4.0.6
  syncfusion_flutter_pdfviewer: ^20.1.51-beta

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  mobx_codegen: ^2.0.5+2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/