import 'package:flutter_lettutor/models/subject.dart';

class Constant {
  static const List<String> Countries = [
    "Vietnam",
    "Laos",
    "Cambodia",
    "America",
    "China",
    "Russia",
    "Argentina",
    "England",
    "Philippines",
    "Malaysia",
    "Indonesia",
    "Australia",
    "Italy",
    "Hungary",
    "Slovakia",
    "Slovenia",
    "Armenia",
    "India",
    "Singapore",
    "Myanmar",
    "France",
    "Germany",
    "Mongol",
    "Canada",
    "Japan",
    "Korean",
    "Nepal",
    "Bhutan",
    "Brazil",
    "Venezuela",
    "Mexico",
    "Uruguay",
    "Paraguay",
    "Denmark",
    "Sweden",
    "Switzerland",
    "Iceland",
    "Ireland",
    "Scotland",
    "Wales",
    "Spain",
    "Portugal",
    "Greece",
    "Turkey",
    "Arab Saudi",
    "UAE",
    "Qatar",
    "Syria",
    "Afghanistan",
    "Israel",
    "Pakistan",
    "Palestine",
    "Iran",
    "Iraq",
    "Libya",
    "South Africa",
    "Congo",
    "Nigeria",
    "Cameroon",
    "Ethiopia",
    "Egypt",
  ];

  static const Map<String, String> Levels = {
    "0": "ANY LEVEL",
    "1": "BEGINNER",
    "2": "HIGHER_BEGINNER",
    "3": "PRE_INTERMEDIATE",
    "4": "INTERMEDIATE",
    "5": "UPPER_INTERMEDIATE",
    "6": "ADVANCED",
    "7": "PROFICIENCY"
  };

  static const List<String> Categories = [
    "For studying abroad",
    "English for Traveling",
    "Conversational English",
    "English for Beginners"
        "Business English",
    "STARTERS",
    "English for Kid",
    "PET",
    "KET",
    "MOVERS",
    "FLYERS",
    "TOEFL",
    "TOEIC"
        "IETLS",
  ];

  static const List<String> Skills = [
    "Business English",
    "English for kids",
    "Conversation English",
    "STARTERS",
    "MOVERS",
    "FLYERS",
    "KET",
    "PET",
    "IETLS",
    "TOEFL",
    "TOEIC"
  ];

  static List<Subject> LearnTopics = [
    Subject(3, "english-for-kids", "English for Kids"),
    Subject(4, "business-english", "Business English"),
    Subject(5, "conversational-english", "Conversational English"),
  ];

  static List<Subject> TestPreparations = [
    Subject(1, "starters", "STARTERS"),
    Subject(2, "movers", "MOVERS"),
    Subject(3, "flyers", "FLYERS"),
    Subject(4, "ket", "KET"),
    Subject(5, "pet", "PET"),
    Subject(6, "ielts", "IELTS"),
    Subject(7, "toefl", "TOEFL"),
    Subject(8, "toeic", "TOEIC"),
  ];

  static List<String> Specialties = [
    "english-for-kids",
    "business-english",
    "conversational-english",
    "starters",
    "movers",
    "flyers",
    "ket",
    "pet",
    "ielts",
    "toefl",
    "toeic"
  ];

  static const Map IsoLangs = {
    "ab": "Abkhaz",
    "aa": "Afar",
    "af": "Afrikaans",
    "ak": "Akan",
    "sq": "Albanian",
    "am": "Amharic",
    "ar": "Arabic",
    "an": "Aragonese",
    "hy": "Armenian",
    "as": "Assamese",
    "av": "Avaric",
    "ae": "Avestan",
    "ay": "Aymara",
    "az": "Azerbaijani",
    "bm": "Bambara",
    "ba": "Bashkir",
    "eu": "Basque",
    "be": "Belarusian",
    "bn": "Bengali",
    "bh": "Bihari",
    "bi": "Bislama",
    "bs": "Bosnian",
    "br": "Breton",
    "bg": "Bulgarian",
    "my": "Burmese",
    "ca": "Valencian",
    "ch": "Chamorro",
    "ce": "Chechen",
    "ny": "Chichewa",
    "zh": "Chinese",
    "cv": "Chuvash",
    "kw": "Cornish",
    "co": "Corsican",
    "cr": "Cree",
    "hr": "Croatian",
    "cs": "Czech",
    "da": "Danish",
    "dv": "Divehi",
    "nl": "Dutch",
    "en": "English",
    "eo": "Esperanto",
    "et": "Estonian",
    "ee": "Ewe",
    "fo": "Faroese",
    "fj": "Fijian",
    "fi": "Finnish",
    "fr": "French",
    "gl": "Galician",
    "ka": "Georgian",
    "de": "German",
    "el": "Greek",
    "he": "Hebrew",
    "hz": "Herero",
    "hi": "Hindi",
    "ho": "Hiri Motu",
    "hu": "Hungarian",
    "ia": "Interlingua",
    "id": "Indonesian",
    "ga": "Irish",
    "ig": "Igbo",
    "ik": "Inupiaq",
    "io": "Ido",
    "is": "Icelandic",
    "it": "Italian",
    "iu": "Inuktitut",
    "ja": "Japanese",
    "jv": "Javanese",
    "kn": "Kannada",
    "ko": "Korean",
    "ku": "Kurdish",
    "kj": "Kwanyama",
    "la": "Latin",
    "ln": "Lingala",
    "lo": "Lao",
    "lv": "Latvian",
    "fa": "Persian",
    "pl": "Polish",
    "pt": "Portuguese",
    "rm": "Romansh",
    "ro": "Romanian",
    "ru": "Russian",
    "se": "Northern Sami",
    "sr": "Serbian",
    "gd": "Scottish Gaelic",
    "sk": "Slovak",
    "sl": "Slovene",
    "so": "Somali",
    "st": "Southern Sotho",
    "es": "Spanish",
    "su": "Sundanese",
    "sv": "Swedish",
    "ta": "Tamil",
    "te": "Telugu",
    "tg": "Tajik",
    "th": "Thai",
    "tk": "Turkmen",
    "tr": "Turkish",
    "ty": "Tahitian",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "uz": "Uzbek",
    "ve": "Venda",
    "vi": "Vietnamese",
    "wa": "Walloon",
    "cy": "Welsh",
    "fy": "Western Frisian",
    "za": "Zhuang, Chuang",
  };

  static const List<String> Interests = ["Sport", "Music", "Technology", "Art", "Movie", "Book", "Travel", "Martial Art", "Coffee"];

  static const List<String> Educations = ["MBA", "MBS", "Prof", "Dr"];
}
