const List<String> countries = [
  "Vietnam",
  "Laos",
  "Cambodia",
  "America",
  "China",
  "Russia",
  "Argentina",
  "England",
  "Philippines",
  "Malaysia",
  "Indonesia",
  "Australia",
  "Italy",
  "Hungary",
  "Slovakia",
  "Slovenia",
  "Armenia",
  "India",
  "Singapore",
  "Myanmar",
  "France",
  "Germany",
  "Mongol",
  "Canada",
  "Japan",
  "Korean",
  "Nepal",
  "Bhutan",
  "Brazil",
  "Venezuela",
  "Mexico",
  "Uruguay",
  "Paraguay",
  "Denmark",
  "Sweden",
  "Switzerland",
  "Iceland",
  "Ireland",
  "Scotland",
  "Wales",
  "Spain",
  "Portugal",
  "Greece",
  "Turkey",
  "Arab Saudi",
  "UAE",
  "Qatar",
  "Syria",
  "Afghanistan",
  "Israel",
  "Pakistan",
  "Palestine",
  "Iran",
  "Iraq",
  "Libya",
  "South Africa",
  "Congo",
  "Nigeria",
  "Cameroon",
  "Ethiopia",
  "Egypt",
];

const List<String> levels = [
  "Beginner",
  "High-Beginner",
  "Pre-Intermediate",
  "Intermediate",
  "Upper Intermediate",
  "Advanced",
  "Proficiency"
];

const List<String> skills = [
  "Business English",
  "English for kids",
  "Conversation English",
  "STARTERS",
  "MOVERS",
  "FLYERS",
  "KET",
  "PET",
  "IETLS",
  "TOEFL",
  "TOEIC",
];

const List<String> interests = [
  "Sport", "Music", "Technology", "Art", "Movie", "Book", "Travel", "Martial Art", "Coffee"
];

const List<String> educations = [
  "MBA", "MBS", "Prof", "Dr"
];
